# Generated by Django 6.0.1 on 2026-01-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_points_user_xp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_plus',
            field=models.BooleanField(default=False, help_text='Define se o usuário possui acesso liberado aos conteúdos Premium.', verbose_name='Assinante Plus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ru',
            field=models.CharField(help_text='Identificador único do aluno para o TCC.', max_length=15, unique=True, verbose_name='Registro Universitário (RU)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Saldo de XP acumulado'),
        ),
    ]
