# Generated by Django 6.0.1 on 2026-01-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_is_plus_alter_user_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_plus',
            field=models.BooleanField(default=False, verbose_name='Assinante Plus'),
        ),
    ]
