# Generated by Django 6.0.1 on 2026-01-19 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Trilha')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Capítulo')),
                ('content', models.TextField(verbose_name='Conteúdo da Aula')),
                ('xp_value', models.PositiveIntegerField(default=50, verbose_name='Valor em XP')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='gamification.trail')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserMedal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('medal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.medal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_medals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'medal')},
            },
        ),
    ]
