# Generated by Django 6.0.1 on 2026-01-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_trail_chapter_usermedal'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da Vídeo Aula (YouTube/Vimeo)'),
        ),
    ]
