# Generated by Django 6.0.1 on 2026-01-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_chapter_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermedal',
            options={'verbose_name': 'Medalha do Usuário', 'verbose_name_plural': 'Medalhas dos Usuários'},
        ),
        migrations.AlterField(
            model_name='usermedal',
            name='earned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Conquista'),
        ),
    ]
