# Generated by Django 6.0.1 on 2026-01-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_alter_chapter_slug_alter_trail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Vídeo Aula'),
        ),
    ]
