# Generated by Django 6.0.1 on 2026-01-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_alter_chapter_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order'], 'verbose_name': 'Capítulo', 'verbose_name_plural': 'Capítulos'},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name': 'Progresso do Aluno', 'verbose_name_plural': 'Progressos dos Alunos'},
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_premium',
            field=models.BooleanField(default=True, verbose_name='Conteúdo Pago'),
        ),
        migrations.AddField(
            model_name='trail',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Trilha Premium'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo Markdown'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('trail', 'title')},
        ),
    ]
