# Generated by Django 6.0.1 on 2026-01-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_alter_chapter_options_alter_userprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Progresso do Aluno', 'verbose_name_plural': 'Progressos dos Alunos'},
        ),
        migrations.AddField(
            model_name='userprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
