# Generated by Django 6.0.1 on 2026-01-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0009_alter_userprogress_options_userprogress_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trails/'),
        ),
        migrations.AddField(
            model_name='trail',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
    ]
