# Generated by Django 6.0.1 on 2026-01-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0010_trail_image_trail_total_xp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermedal',
            options={'verbose_name': 'Medalha do Usuário', 'verbose_name_plural': 'Medalhas dos Usuários'},
        ),
    ]
