# Generated by Django 6.0.1 on 2026-01-27 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0011_alter_usermedal_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enunciado', models.TextField(verbose_name='Pergunta')),
                ('xp_recompensa', models.PositiveIntegerField(default=10, verbose_name='XP por Acerto')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='gamification.chapter')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Texto da Alternativa')),
                ('e_correta', models.BooleanField(default=False, verbose_name='É a resposta correta?')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='gamification.questao')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
            },
        ),
    ]
